### ISSUE TITLE
confusing about different "pyterrier"s

### ISSUE THREAD

**Issue by cmacdonald** [dfurtado/pyterrier#19]
Hi,

I'm the maintainer of PyTerrier - https://github.com/terrier-org/pyterrier & https://pyterrier.readthedocs.io/en/latest/
PyTerrier started as python bindings for our long-existing Terrier project (http://terrier.org), hence the naming.

As `pip install pyterrier` naturally points to your project, which of course existed before ours, sometimes our users get confused. Our natural workflow is
```python
! pip install python-terrier
import pyterrier as pt
pt.init()
````

I was wondering if you would accept a PR for a init() method in https://github.com/dfurtado/pyterrier/blob/master/pyterrier/__init__.py that would tell any confused users that they installed the wrong platform. This would not have any impact on your users, as the method would remain undocumented for your platform. Something like:

```python

def init(*args, **kwargs):
  from warnings import warn
  warn("If you are looking for the information retrieval platform, you should run 'pip install python-terrier' instead")

```

Craig

**Comment by dfurtado** [comment]
Hi @cmacdonald

Sorry about the late reply. 

Oh that's bad! I can definitely accept a PR for this change. 

I wish I could help you guys better by removing the package from PyPI but unfortunately I have mentioned the project on my book, so it is hard to do these kind of changes. 

I think it is even possible to show the message during the installation.

//Daniel

**Comment by cmacdonald** [comment]
Thanks for your understanding Daniel. I shall prepare and submit a PR addressing both init() and setup.py as discussed.

**Comment by cmacdonald** [comment]
>Thanks for the fixed @cmacdonald !! I hope this fix will help your users and let me know if there is something more I can help with. 👍🏼

Thank you for your understanding and fast reaction on #20 @dfurtado. Closing this issue.

**Comment by dfurtado** [comment]
Thanks @cmacdonald

FYI I just release a new version on PyPI with these changes. So now your users will get an error when calling the init() in case they installed the wrong framework. :)

**Comment by cmacdonald** [comment]
Fab, I just checked in Colab, and it works perfectly. Once again, thanks for your help.
