### ISSUE TITLE
Support the template engine Jade and Mustache

### ISSUE THREAD

**Issue by dfurtado** [dfurtado/pyterrier#3]
The default template engine used by the framework is Jinja2, it would add a lot of value if we could have a renderer class for Jade and Mustache as well.

It should be pretty straight forward to implement it, the only requirement is to create a class that inherits from `pyterrier.renderers.BaseRenderer`

With these new renderers implemented, we could extend the CLI to add the option to chose which renderer the application will use.

**Comment by tenorz007** [comment]
Hello @dfurtado 

With regards to supporting the moustache template, I noticed the python port hasn't been updated in 3 years, would you still want to go ahead with supporting it?

**Comment by dfurtado** [comment]
Hi @tenorz007 
Ah ok, maybe isn't worth trying to add support for that. However, I think it would be very nice to have Jade (PyJade) support and also (if possible) support for the Django templates as well so Django users wouldn't need to re-write their templates.

**Comment by tenorz007** [comment]
I think PyJade can be rendered using the Jinja2Renderer, all that would take would be adding it to the list of extensions and specifying the directory....
