### ISSUE TITLE
Multiple HTTP verb support for routes 

### ISSUE THREAD

**Issue by tenorz007** [dfurtado/pyterrier#6]
Support for handling multiple request types to a route by a single method as stated [here](https://github.com/dfurtado/pyterrier/issues/5#issuecomment-325893204)

Example:
```python
@app.get('/', accepts=[app.post])
def update(self):
    pass
```

**Comment by dfurtado** [comment]
Do you want to work on this issue @tenorz007 ? I can assign it to you.

**Comment by tenorz007** [comment]
I am fine with taking a shot at it, although it will take me some time to implement it anyway.

**Comment by tenorz007** [comment]
@dfurtado I see this feature has been added, so this issue can be closed!

**Comment by dfurtado** [comment]
@tenorz007 Hi! It is not entirely implemented yet. Still some parts that need changes I'm working on it. :)

**Comment by tenorz007** [comment]
@dfurtado Alright, I just had a broad look at it, so I thought it was done!
